"""
Module for generating PDF reports and visualizations.
Preserved from original Streamlit version.
"""

import io
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from wordcloud import WordCloud
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
from reportlab.lib.colors import green, red, yellow, black, grey, white, blue, HexColor
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as ReportLabImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
import numpy as np
from typing import Dict
import matplotlib
matplotlib.use('Agg')  # Use non-interactive backend
import matplotlib.pyplot as plt
import json

# Import for consistent color logic
from modules.sentiment_analyzer import get_score_color

# New constants for risk messaging
RISK_WARNING_SHORT = "Strong indicators of potential risk identified"
RISK_ADVICE_UI = "Exercise caution and conduct further independent research before downloading, using, or trusting this app. Consider reporting the app directly to the Google Play Store or relevant authorities if you have concerns. Look for red flags such as unclear developer history, excessive permissions, or consistent scam reports elsewhere."

# Disclaimer text
DISCLAIMER_TEXT = "Disclaimer: This analysis is based on publicly available user reviews and does not involve deep technical analysis of the app's code or official investigative findings. The risk assessment is generated by your specified threshold for negative sentiment. Please conduct your own due diligence."
DISCLAIMER_LINK = "https://github.com/Ian-Lusule/fraud-app-analyzer"

def create_sentiment_trend_chart(trend_df: pd.DataFrame, for_pdf: bool = True) -> plt.Figure:
    """
    Generates a matplotlib figure for sentiment trend over time.

    Args:
        trend_df (pd.DataFrame): DataFrame with sentiment counts indexed by date.
        for_pdf (bool): If True, optimizes for PDF embedding (smaller, no interactive elements).

    Returns:
        matplotlib.figure.Figure: The generated matplotlib figure.
    """
    fig, ax = plt.subplots(figsize=(8, 4) if for_pdf else (10, 6))
    if not trend_df.empty:
        trend_df.plot(ax=ax, grid=True, legend=True)
        ax.set_title("Sentiment Trend Over Time", fontsize=10 if for_pdf else 14, pad=5)
        ax.set_xlabel("Date", fontsize=8 if for_pdf else 12)
        ax.set_ylabel("Number of Reviews", fontsize=8 if for_pdf else 12)
        ax.tick_params(axis='x', labelsize=7 if for_pdf else 10)
        ax.tick_params(axis='y', labelsize=7 if for_pdf else 10)
        ax.legend(title='Sentiment', fontsize=7 if for_pdf else 10)
        ax.grid(True, linestyle='-', alpha=0.7)
    else:
        ax.text(0.5, 0.5, "No data for sentiment trend.", horizontalalignment='center', verticalalignment='center',
                transform=ax.transAxes, fontsize=10 if for_pdf else 12, color='gray')
        ax.set_title("Sentiment Trend Over Time (No Data)", fontsize=10 if for_pdf else 14, pad=5)
        ax.set_xticks([])
        ax.set_yticks([])
    fig.tight_layout()
    return fig

def create_word_cloud_image(all_text: str, for_pdf: bool = True) -> plt.Figure:
    """
    Generates a matplotlib figure for a word cloud.

    Args:
        all_text (str): The concatenated text for the word cloud.
        for_pdf (bool): If True, optimizes for PDF embedding.

    Returns:
        matplotlib.figure.Figure: The generated matplotlib figure.
    """
    fig, ax = plt.subplots(figsize=(8, 4) if for_pdf else (10, 5))
    if all_text.strip():
        wordcloud = WordCloud(width=800, height=400, background_color="white").generate(all_text)
        ax.imshow(wordcloud, interpolation="bilinear")
    else:
        ax.text(0.5, 0.5, "No review text available for keyword analysis.", horizontalalignment='center', verticalalignment='center',
                transform=ax.transAxes, fontsize=10 if for_pdf else 12, color='gray')
    ax.axis("off")
    fig.tight_layout()
    return fig

def generate_single_app_pdf_report(
    app_id: str,
    app_details: Dict,
    filtered_df: pd.DataFrame,
    sentiment_counts: pd.Series,
    positive_pct: float,
    negative_pct: float,
    neutral_pct: float,
    app_rating_score: float,
    playstore_score: float,
    fraud_threshold: float,
    trend_df: pd.DataFrame,
    all_text: str,
    report_df: pd.DataFrame = None,
    classification_metrics: dict = None
) -> io.BytesIO:
    """
    Generates a PDF report for a single app analysis.
    
    Args:
        app_id (str): App ID.
        app_details (Dict): App details dictionary.
        filtered_df (pd.DataFrame): Filtered reviews DataFrame.
        sentiment_counts (pd.Series): Sentiment counts.
        positive_pct (float): Positive percentage.
        negative_pct (float): Negative percentage.
        neutral_pct (float): Neutral percentage.
        app_rating_score (float): App rating score.
        playstore_score (float): Play Store score.
        fraud_threshold (float): Fraud threshold.
        trend_df (pd.DataFrame): Trend data.
        all_text (str): All review text concatenated.
        report_df (pd.DataFrame): Additional report data.
        
    Returns:
        io.BytesIO: PDF buffer.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, 
                           rightMargin=inch/2, leftMargin=inch/2,
                           topMargin=inch/2, bottomMargin=inch/2)
    
    story = []
    styles = getSampleStyleSheet()

    # Defensive handling: ensure classification_metrics is a dict-like object
    if classification_metrics:
        # If stored as JSON string, try to parse it
        if isinstance(classification_metrics, str):
            try:
                classification_metrics = json.loads(classification_metrics)
            except Exception:
                classification_metrics = {}
        # If it's an object with attributes (e.g., SimpleNamespace), convert to dict
        elif not hasattr(classification_metrics, 'get') and hasattr(classification_metrics, '__dict__'):
            try:
                classification_metrics = vars(classification_metrics)
            except Exception:
                classification_metrics = {}
        # If it's not dict-like at this point, drop it
        elif not hasattr(classification_metrics, 'get'):
            classification_metrics = {}
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=16,
        spaceAfter=12,
        textColor=HexColor('#2c3e50')
    )
    
    story.append(Paragraph(f"Fraud App Analyzer Report", title_style))
    story.append(Paragraph(f"App: {app_details.get('title', 'Unknown App')}", styles['Heading2']))
    story.append(Paragraph(f"App ID: {app_id}", styles['Normal']))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    story.append(Spacer(1, 12))
    
    # App Details Table
    story.append(Paragraph("App Details", styles['Heading3']))
    
    app_data = [
        ["Developer:", app_details.get('developer', 'N/A')],
        ["Installs:", app_details.get('installs', 'N/A')],
        ["Price:", "Free" if app_details.get('free', True) else f"${app_details.get('price', 0)}"],
        ["Play Store URL:", app_details.get('url', 'N/A')],
        ["Country:", app_details.get('country', 'N/A')]
    ]
    
    app_table = Table(app_data, colWidths=[2*inch, 4*inch])
    app_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HexColor('#f8f9fa')),
        ('TEXTCOLOR', (0, 0), (-1, -1), black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, grey)
    ]))
    
    story.append(app_table)
    story.append(Spacer(1, 12))
    
    # Metrics Section
    story.append(Paragraph("Analysis Metrics", styles['Heading3']))
    
    metrics_data = [
        ["Metric", "Value", "Threshold"],
        ["Total Reviews Analyzed:", str(len(filtered_df)), "N/A"],
        ["Positive Sentiment:", f"{positive_pct:.1f}%", f"> {fraud_threshold}%"],
        ["Negative Sentiment:", f"{negative_pct:.1f}%", f"< {fraud_threshold}%"],
        ["Neutral Sentiment:", f"{neutral_pct:.1f}%", "N/A"],
        ["App Rating Score:", f"{app_rating_score:.1f}%", "N/A"],
        ["Play Store Score:", f"{playstore_score:.1f}%", "N/A"]
    ]

    # Add classification metrics if provided — coerce safely to dict-like `cm`
    cm = {}
    try:
        if classification_metrics:
            if isinstance(classification_metrics, str):
                try:
                    cm = json.loads(classification_metrics)
                except Exception:
                    cm = {}
            elif hasattr(classification_metrics, 'get'):
                cm = classification_metrics
            elif hasattr(classification_metrics, '__dict__'):
                try:
                    cm = vars(classification_metrics)
                except Exception:
                    cm = {}
    except Exception:
        cm = {}

    if cm:
        metrics_data.append(["Accuracy:", f"{cm.get('accuracy',0.0)*100:.2f}%", "N/A"])
        metrics_data.append(["Precision:", f"{cm.get('precision',0.0)*100:.2f}%", "N/A"])
        metrics_data.append(["Recall:", f"{cm.get('recall',0.0)*100:.2f}%", "N/A"])
        metrics_data.append(["F1 Score:", f"{cm.get('f1',0.0)*100:.2f}%", "N/A"])
    
    metrics_table = Table(metrics_data, colWidths=[2*inch, 1.5*inch, 1.5*inch])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HexColor('#343a40')),
        ('TEXTCOLOR', (0, 0), (-1, 0), white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), white),
        ('TEXTCOLOR', (0, 1), (-1, -1), black),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, grey),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER')
    ]))
    
    story.append(metrics_table)
    story.append(Spacer(1, 12))
    
    # Risk Assessment
    story.append(Paragraph("Risk Assessment", styles['Heading3']))
    
    if negative_pct > fraud_threshold:
        risk_text = f"<font color='red'><b>🚨 {RISK_WARNING_SHORT}</b></font><br/>"
        risk_text += f"Negative sentiment ({negative_pct:.1f}%) exceeds your threshold of {fraud_threshold}%.<br/>"
        risk_text += RISK_ADVICE_UI
        story.append(Paragraph(risk_text, styles['Normal']))
    else:
        story.append(Paragraph("<font color='green'><b>✅ No significant risk indicators found based on current analysis settings.</b></font>", styles['Normal']))
    
    story.append(Spacer(1, 12))
    
    # Visualizations
    story.append(Paragraph("Visualizations", styles['Heading3']))
    
    # Sentiment Trend Chart
    if not trend_df.empty:
        trend_fig = create_sentiment_trend_chart(trend_df, for_pdf=True)
        trend_buffer = io.BytesIO()
        trend_fig.savefig(trend_buffer, format='png', dpi=150)
        trend_buffer.seek(0)
        trend_img = ReportLabImage(trend_buffer, width=6*inch, height=3*inch)
        story.append(trend_img)
        plt.close(trend_fig)
        story.append(Spacer(1, 12))
    
    # Word Cloud
    if all_text.strip():
        wordcloud_fig = create_word_cloud_image(all_text, for_pdf=True)
        wc_buffer = io.BytesIO()
        wordcloud_fig.savefig(wc_buffer, format='png', dpi=150)
        wc_buffer.seek(0)
        wc_img = ReportLabImage(wc_buffer, width=6*inch, height=3*inch)
        story.append(wc_img)
        plt.close(wordcloud_fig)
        story.append(Spacer(1, 12))
    
    # Sample Reviews
    story.append(Paragraph("Sample Reviews", styles['Heading3']))
    
    if not filtered_df.empty:
        sample_reviews = filtered_df.head(10)[['content', 'sentiment', 'score']]
        sample_data = [["Review Excerpt", "Sentiment", "Rating"]]
        
        for _, row in sample_reviews.iterrows():
            content = row['content'][:100] + "..." if len(row['content']) > 100 else row['content']
            sample_data.append([content, row['sentiment'], str(row['score'])])
        
        sample_table = Table(sample_data, colWidths=[3.5*inch, 1*inch, 1*inch])
        sample_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), HexColor('#343a40')),
            ('TEXTCOLOR', (0, 0), (-1, 0), white),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BACKGROUND', (0, 1), (-1, -1), white),
            ('TEXTCOLOR', (0, 1), (-1, -1), black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 9),
            ('GRID', (0, 0), (-1, -1), 0.5, grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [white, HexColor('#f8f9fa')])
        ]))
        
        story.append(sample_table)
        story.append(Spacer(1, 12))
    
    # Disclaimer
    story.append(Paragraph("Disclaimer", styles['Heading4']))
    disclaimer_style = ParagraphStyle(
        'DisclaimerStyle',
        parent=styles['Normal'],
        fontSize=8,
        textColor=grey,
        alignment=TA_CENTER
    )
    story.append(Paragraph(DISCLAIMER_TEXT, disclaimer_style))
    story.append(Paragraph(f"For more information: {DISCLAIMER_LINK}", disclaimer_style))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer

def generate_comparison_pdf(app1_data: Dict, app2_data: Dict) -> io.BytesIO:
    """
    Generate PDF for app comparison.
    
    Args:
        app1_data (Dict): First app data.
        app2_data (Dict): Second app data.
        
    Returns:
        io.BytesIO: PDF buffer.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Title
    story.append(Paragraph("App Comparison Report", styles['Heading1']))
    story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    story.append(Spacer(1, 12))
    
    # Comparison Table
    story.append(Paragraph("Comparison Metrics", styles['Heading2']))
    
    comparison_data = [
        ["Metric", app1_data['app_name'], app2_data['app_name']],
        ["Total Reviews", str(app1_data['total_reviews']), str(app2_data['total_reviews'])],
        ["Positive %", f"{app1_data['positive_pct']:.1f}%", f"{app2_data['positive_pct']:.1f}%"],
        ["Negative %", f"{app1_data['negative_pct']:.1f}%", f"{app2_data['negative_pct']:.1f}%"],
        ["Neutral %", f"{app1_data['neutral_pct']:.1f}%", f"{app2_data['neutral_pct']:.1f}%"],
        ["App Rating Score", f"{app1_data['app_rating_score']:.1f}%", f"{app2_data['app_rating_score']:.1f}%"],
        ["Play Store Score", f"{app1_data['playstore_score']:.1f}%", f"{app2_data['playstore_score']:.1f}%"]
    ]
    
    comparison_table = Table(comparison_data)
    comparison_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HexColor('#343a40')),
        ('TEXTCOLOR', (0, 0), (-1, 0), white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), white),
        ('GRID', (0, 0), (-1, -1), 1, grey)
    ]))
    
    story.append(comparison_table)
    story.append(Spacer(1, 12))
    
    # Build PDF
    doc.build(story)
    buffer.seek(0)
    return buffer